apiVersion: apps/v1
kind: Deployment
metadata:
  name: csc-admin-portal
  labels:
    app: csc-admin-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csc-admin-portal
  template:
    metadata:
      labels:
        app: csc-admin-portal
    spec:
      containers:
      - name: csc-admin-portal
        image: public.ecr.aws/k9a0m9b4/stinoy:latest  # Update the tag as needed
        ports:
        - containerPort: 80

